apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-app
  labels:
    app: timesheet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timesheet
  template:
    metadata:
      labels:
        app: timesheet
    spec:
      containers:
        - name: timesheet-container
          image: sondeshakiri320/timesheetproject:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/timesheet2021?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: son
            - name: SPRING_DATASOURCE_PASSWORD
              value: sonpassword

