# Timesheet Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-deployment
  labels:
    app: timesheet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timesheet
  template:
    metadata:
      labels:
        app: timesheet
    spec:
      containers:
        - name: timesheet-container
          image: msaidc/timesheet:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb-service:3306/timesheet2021?useSSL=false&allowPublicKeyRetrieval=true  # Update with your DB service
            - name: SPRING_DATASOURCE_USERNAME
              value: said
            - name: SPRING_DATASOURCE_PASSWORD
              value: "55307062"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"