apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-deployment
  labels:
    app: timesheet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timesheet
  template:
    metadata:
      labels:
        app: timesheet
    spec:
      containers:
        - name: timesheet-container
          image: meriam209/timesheet:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
