version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: azerty12346                # Root password
      MYSQL_DATABASE: testdb                 # Database name
      MYSQL_USER: testuser                             # Database user
      MYSQL_PASSWORD: testpassword                     # User password
    ports:
      - "3307:3306"                                # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql                  # Persistent storage for data

  app:
    image: ar0uabendaya/timesheet:latest           # Replace with your Docker image
    container_name: timesheet_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpassword
    ports:
      - "8081:8081"                                    # Expose app port to localhost

volumes:
  mysql_data:
