version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: timesheet2021
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    networks:
      - spring_network

  tomcat:
    image: sondeshakiri320/timesheetproject:latest  
    container_name: tomcat
    ports:
      - "8082:8081"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/timesheet2021
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - mysql
    networks:
      - spring_network
    volumes:
      - ./target/SpringMVC.war:/usr/local/tomcat/webapps/SpringMVC.war  

networks:
  spring_network:
    driver: bridge
