version: '3.8'

services:
  spring-app:
    image: spring-app-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/timesheet2021?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: son
      SPRING_DATASOURCE_PASSWORD: sonpassword
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timesheet2021
      MYSQL_USER: son
      MYSQL_PASSWORD: sonpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
