apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 5Gi  # Adjust size as necessary
  accessModes:
    - ReadWriteOnce
  hostPath:  # Change this to a suitable storage type for your environment
    path: /mnt/data/mariadb  # Local path on the node, adjust based on your cluster setup
  persistentVolumeReclaimPolicy: Retain
