apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: "timesheet2021"
            - name: MYSQL_USER
              value: "username"              
            - name: MYSQL_PASSWORD
              value: "password"     
          ports:
            - containerPort: 3306
