apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD 
              value: "root"     
            - name: MYSQL_DATABASE
              value: "timesheet2021"
            - name: MYSQL_USER
              value: "son"
            - name: MYSQL_PASSWORD
              value: "sonpassword"    
          ports:
            - containerPort: 3306
