apiVersion: v1
kind: Service
metadata:
  name: timesheet-service
  labels:
    app: timesheet
spec:
  selector:
    app: timesheet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
