apiVersion: v1
kind: Service
metadata:
  name: timesheet-service
spec:
  type: LoadBalancer
  selector:
    app: timesheet
  ports:
    - protocol: TCP
      port: 80           # External port of the LoadBalancer
      targetPort: 8080      # Internal port on the pod
