apiVersion: v1
kind: Service
metadata:
  name: timesheet-service
spec:
  type: NodePort
  selector:
    app: timesheet
  ports:
    - protocol: TCP
      port: 8080           # external port of the pod
      targetPort: 8080      # internal port of the pod
      nodePort: 30000       # Port exposé sur le nœud Kubernetes (entre 30000 et 32767)
