apiVersion: v1
kind: Service
metadata:
  name: timesheet-app-service
  labels:
    app: timesheet
spec:
  selector:
    app: timesheet
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer

